# Generated by Django 3.2.3 on 2021-05-17 17:28

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NPOUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_type', models.IntegerField(choices=[(1, 'ADMIN'), (2, 'CLIENT')], default=2, verbose_name='Тип пользовотеля')),
                ('user_name', models.CharField(max_length=100, unique=True, verbose_name='user_name')),
                ('email', models.EmailField(max_length=100, null=True, verbose_name='email')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last_name')),
                ('data_joined', models.DateTimeField(auto_now_add=True, verbose_name='data_joined')),
                ('is_active', models.DateTimeField(default=True, verbose_name='is_active')),
                ('is_staff', models.DateTimeField(default=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователь',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
